version: '3.8'

services:
  mongo1:
    container_name: mongo1
    image: mongo
    restart: always
    ports:
      - 27019:27017
    command: --replSet rs1
    volumes:
      - mongoVolume:/data/db
    networks:
      - mongo-network

  nestjs:
    container_name: nestjs
    build: .
    environment:
      - PORT=3000
      - DATABASE=mongodb://mongo1:27017/nest-upskilling?directConnection=true&replicaSet=rs1
    ports:
      - 3000:3000
    depends_on:
      - mongo1
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - mongo-network

volumes:
  mongoVolume:

networks:
  mongo-network:
    driver: bridge
